version: "3.0"

# Services to run
services:
  mongo_strategy: # name of BD service
    image: mongo
    container_name: node_sms
    ports:
      - 27017:27017
    volumes:
      - mongonodesms:/data/configdb
      - mongonodesms:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  mongonodesms:
