version: "3.0"

services:
  # nombre del servicio
  mongodb:
    image: mongo
    container_name: mongo_db_container_kb
    ports:
      # local --> contenedor
      - 27017:27017
    restart: always
    volumes:
      - mongodockerkb:/data/configdb
      - mongodockerkb:/data/db

  api:
    build: .
    container_name: api_container_kb
    ports:
      # local --> contenedor
      - 6000:6000
    depends_on:
      - mongodb
    restart: always
    # opcional ya que ayuda a desarrollar con el docker compose ejecutandose
    volumes:
      - .:/usr/src/app

volumes:
  mongodockerkb:
