version: "3.0"

# Services to run
services:
  mongo: # name of BD service
    image: mongo
    container_name: mongo_db_artillery
    ports:
      - 27017:27017
    volumes:
      - mongoartillery:/data/configdb
      - mongoartillery:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  mongoartillery:
