version: "3.0"

# Services to run
services:
  mongo_strategy: # name of BD service
    image: mongo
    container_name: mongo_db_passport_jwt
    ports:
      - 27017:27017
    volumes:
      - mongostrategyjwt:/data/configdb
      - mongostrategyjwt:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  mongostrategyjwt:
