version: "3.0"

# Services to run
services:
  mongo_jwt: # name of BD service
    image: mongo
    container_name: mongo_db_jwt_avz
    ports:
      - 27017:27017
    volumes:
      - mongojwt2:/data/configdb
      - mongojwt2:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  mongojwt2:
