version: '3.0'

services:
  mongo:
    image: mongo
    container_name: mongo_nest_container
    ports:
      - 27017:27017
    volumes:
      - mongonestdb:/data/configdb
      - mongonestdb:/data/db

volumes:
  mongonestdb: