const studentsData = [
  {
    nombre: "Steffen",
    apellido: "Terzo",
    edad: 36,
    dni: "15691240",
    curso: "Programación Backend",
    nota: 9,
    genero: "M",
  },
  {
    nombre: "Jorgan",
    apellido: "Matthis",
    edad: 27,
    dni: "29358120",
    curso: "Programación Frontend",
    nota: 6,
    genero: "M",
  },
  {
    nombre: "Haley",
    apellido: "Proback",
    edad: 34,
    dni: "51241268",
    curso: "Diseño UX/UI",
    nota: 7,
    genero: "M",
  },
  {
    nombre: "Michelina",
    apellido: "Beaglehole",
    edad: 34,
    dni: "24614567",
    curso: "Diseño UX/UI",
    nota: 6,
    genero: "F",
  },
  {
    nombre: "Jeralee",
    apellido: "Postans",
    edad: 26,
    dni: "97212450",
    curso: "Programación Frontend",
    nota: 6,
    genero: "F",
  },
  {
    nombre: "Jordain",
    apellido: "Kerner",
    edad: 35,
    dni: "41262234",
    curso: "Programación Backend",
    nota: 5,
    genero: "M",
  },
  {
    nombre: "Harriett",
    apellido: "Skeene",
    edad: 33,
    dni: "21245129",
    curso: "Programación Backend",
    nota: 10,
    genero: "F",
  },
  {
    nombre: "Andie",
    apellido: "McIlrath",
    edad: 20,
    dni: "59127389",
    curso: "Programación Frontend",
    nota: 9,
    genero: "M",
  },
  {
    nombre: "Sapphira",
    apellido: "Arnholtz",
    edad: 17,
    dni: "03128893",
    curso: "Programación Backend",
    nota: 5,
    genero: "F",
  },
  {
    nombre: "Terra",
    apellido: "Wadsworth",
    edad: 31,
    dni: "02213850",
    curso: "Diseño UX/UI",
    nota: 10,
    genero: "F",
  },
  {
    nombre: "Rabindranath",
    apellido: "Ferreira",
    edad: 32,
  },
];

module.exports = studentsData;
