version: "3.0"

# Services to run
services:
  mongo_strategy: # name of BD service
    image: mongo
    container_name: mongo_layer_arch_2
    ports:
      - 27017:27017
    volumes:
      - mongolayerarch2:/data/configdb
      - mongolayerarch2:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  mongolayerarch2:
