version: "3.0"

services:
  # nombre del servicio
  mongodb:
    image: mongo
    container_name: mongo_db_payments_gateway
    ports:
      # local --> contenedor
      - 27017:27017
    # restart: always
    volumes:
      - mongopayments:/data/configdb
      - mongopayments:/data/db

  api:
    build: .
    container_name: api_container_payments
    ports:
      # local --> contenedor
      - 5000:5000
    depends_on:
      - mongodb
    # restart: always
    # opcional ya que ayuda a desarrollar con el docker compose ejecutandose
    volumes:
      - .:/usr/src/app

volumes:
  mongopayments:
